In [28]:
import torch
import torchvision
from d2l import torch as d2l
from torch.utils.data import DataLoader
from IPython import display
from torch.utils.tensorboard import SummaryWriter

writer = SummaryWriter('DataLoader')
trans = torchvision.transforms.ToTensor()

mnist_train = torchvision.datasets.FashionMNIST(root = 'E:\Deep_learning\data' , train = True , transform = trans , download = True)
mnist_test = torchvision.datasets.FashionMNIST(root = 'E:\Deep_learning\data' , train = False , transform = trans , download = True)

batch_size = 256

train_iter = DataLoader(mnist_train , batch_size , shuffle = True , num_workers = 0 , drop_last = False)
text_iter = DataLoader(mnist_test , batch_size , shuffle = False , num_workers = 0 , drop_last = False)

for epoch in range(2):
    step = 2
    for data in train_iter:
        img , labels = data
        writer.add_images("test_data_drop_last",img,step)
        step += 1

writer.close()

In [5]:
input = 784
output = 10
w = torch.normal(0 , 0.01 , size = (input,output),requires_grad = True)
b = torch.zeros(input , requires_grad = True)

In [30]:
X = torch.Tensor([[1.0 , 2.0 , 3.0],[4.0 , 5.0 , 6.0]])
X.sum(0 , keepdim = True) , X.sum(1 , keepdim = True)

(tensor([[5., 7., 9.]]),
 tensor([[ 6.],
         [15.]]))

In [31]:
def softmax(X):
    X_exp = torch.exp(X)
    partition = X_exp.sum(1 , keepdim = True)
    return X_exp / partition

In [33]:
X = torch.normal(0, 1, (2, 5))
X_prob = softmax(X)
X_prob, X_prob.sum(1)

(tensor([[0.0184, 0.5177, 0.2706, 0.1307, 0.0627],
         [0.0374, 0.3255, 0.0696, 0.4956, 0.0719]]),
 tensor([1., 1.]))

In [34]:
def net(X):
    return softmax(torch.matmul(X.reshape((-1, W.shape[0])), W) + b)