In [2]:
import torch
from torch import nn
import torch.nn.functional as F

In [5]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self,x):
        return x - x.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [6]:
#将层作为组件合并到构建更复杂的模型中
net = nn.Sequential(nn.Linear(8 , 128),CenteredLayer())
Y = net(torch.rand(4 , 8))
Y.mean()

tensor(-1.8626e-09, grad_fn=<MeanBackward0>)

In [23]:
#带参数的图层
class MyLinear(nn.Module):
    def __init__(self,in_units,units, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.weight = nn.Parameter(torch.randn(in_units , units))
        self.bias = nn.Parameter(torch.randn(units,))
        
    def forward(self,X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)
dense = MyLinear(5 , 3)
dense.weight

Parameter containing:
tensor([[-2.1048, -0.5898,  1.5490],
        [ 1.5089, -0.1569,  3.6192],
        [-2.0959,  0.9194, -1.2340],
        [ 0.5435, -0.8917,  0.7222],
        [-0.6108, -0.2914, -0.2928]], requires_grad=True)

In [24]:
#使用自定义层进行前向传播
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 1.4145, -0.4100,  1.7934],
        [-0.3187, -0.7075, -1.7395],
        [-0.0887,  0.6805,  0.9589],
        [-0.5504, -1.4832,  0.8174],
        [-0.4994, -1.6872, -0.3818]], requires_grad=True)

In [25]:
#使用自定义曾构建模型
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[2.4112],
        [4.5286]])