In [98]:
import torch
from torch import nn
from d2l import torch as d2l

In [99]:
def pool2d(X , pool_Size ,mode='max'):
    p_h,p_w = pool_Size
    Y = torch.zeros((X.shape[0] - p_h + 1,X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i , j] = X[i:i + p_h , j : j + p_w].max()
            if mode == 'avg':
                Y[i , j] = X[i:i + p_h , j : j + p_w].mean()
    return Y 

In [100]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

In [101]:
pool2d(X, (2, 2), 'avg')

tensor([[2., 3.],
        [5., 6.]])

In [102]:
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))#批量大小是1，通道数是1
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [103]:
pool2d = nn.MaxPool2d(3)#pytorch的步幅和池化窗口的大小是相等的
pool2d(X)

tensor([[[[10.]]]])

In [104]:
pool2d = nn.MaxPool2d(3 , padding=1 , stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [105]:
#在处理多通道输入数据时，汇聚层在每个输入通道上单独运算，而不是像卷积层一样在通道上对输入进行汇总。 这意味着汇聚层的输出通道数与输入通道数相同。
X = torch.cat((X, X + 1), 1)#按维数0拼接（竖着拼，按维数1拼接（横着拼）
print(X)

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])


In [106]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])